### ISSUE TITLE
Default workflow raise an error with ComfyUI v0.19.3: raise AttributeError( AttributeError: 'Identity' object has no attribute 'device'

### ISSUE THREAD

**Issue by dijkstrabc** [tackcrypto1031/tk_seethrough#6]
Got this on ComfyUI v0.19.3 (works fine on ComfyUI v0.16.3)

[SeeThrough VRAM] Text encoders loaded to GPU: allocated=0.02GB, reserved=0.06GB
!!! Exception during processing !!! 'Identity' object has no attribute 'device'
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 534, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/execution.py", line 334, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/execution.py", line 308, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 296, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/tk-comfyui-see-through/nodes.py", line 673, in generate
    body_embeds, body_pooled = pipeline.encode_cropped_prompt_77tokens(VALID_BODY_PARTS_V3_BODY)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/comfyui-see-through/see-through/common/modules/layerdiffuse/diffusers_kdiffusion_sdxl.py", line 145, in encode_cropped_prompt_77tokens
    device = self.text_encoder.device
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 1965, in __getattr__
    raise AttributeError(
AttributeError: 'Identity' object has no attribute 'device'

**Comment by tackcrypto1031** [comment]
Hi @dijkstrabc, thanks for the detailed report — this is fixed in **v1.2.9** (commit 265d7ac, pushed to `main`).

## Root cause

Newer `diffusers` (shipped with ComfyUI v0.19.3) silently substitutes `torch.nn.Identity()` as a placeholder for `text_encoder` / `text_encoder_2` when the checkpoint's `model_index.json` skips them. `nn.Identity` has no `.device` attribute (only `CLIPTextModel` does), hence the `AttributeError`.

The diagnostic signal was your VRAM log: `Text encoders loaded to GPU: allocated=0.02GB` — SDXL CLIP encoders are normally ~0.7 GB, so 0.02 GB confirmed the Identity placeholder substitution.

## Fix

Two-layer defence landed:

1. **Fail fast at load time** (`nodes.py`) — both `LoadLayerDiffModel` and `LoadDepthModel` now assert that `text_encoder` has parameters right after `from_pretrained`, with a clear actionable error message instead of a cryptic `AttributeError` deep in the inference path.
2. **Safe device lookup** in `encode_cropped_prompt_77tokens` and Marigold's `encode_empty_text` — uses `next(parameters()).device` instead of `.device`, which is identical on real `CLIPTextModel` but raises a helpful error on empty placeholders.

Regression test added: `tests/test_text_encoder_check.py` (full suite 14/14 passing).

Details: [docs/issue-6-fix.md](https://github.com/tackcrypto1031/tk_seethrough/blob/main/docs/issue-6-fix.md)

## Please update & retest

```
cd ComfyUI/custom_nodes/tk-comfyui-see-through
git pull
```

Then restart ComfyUI and try your workflow again. **Two possible outcomes**:

- **It works** — great, close the issue.
- **You get a new `RuntimeError: text_encoder failed to load (got empty placeholder...)`** — that means the fix correctly detected that your model checkpoint is missing the `text_encoder` / `text_encoder_2` folders (or the `model_index.json` doesn't list them). Please try re-downloading the model, or share your model path layout and we'll investigate further.

Thanks again for the report!

**Comment by dijkstrabc** [comment]
Output remains to be the same after updating to v1.2.9:

AttributeError: 'Identity' object has no attribute 'device'


  File "/root/ComfyUI/execution.py", line 534, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/ComfyUI/execution.py", line 334, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/ComfyUI/execution.py", line 308, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "/root/ComfyUI/execution.py", line 296, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "/root/ComfyUI/custom_nodes/tk-comfyui-see-through/nodes.py", line 694, in generate
    body_embeds, body_pooled = pipeline.encode_cropped_prompt_77tokens(VALID_BODY_PARTS_V3_BODY)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib64/python3.12/site-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/root/ComfyUI/custom_nodes/comfyui-see-through/see-through/common/modules/layerdiffuse/diffusers_kdiffusion_sdxl.py", line 145, in encode_cropped_prompt_77tokens
    device = self.text_encoder.device
             ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib64/python3.12/site-packages/torch/nn/modules/module.py", line 1965, in __getattr__
    raise AttributeError(

**Comment by tackcrypto1031** [comment]
Hi @dijkstrabc,

Thanks for the follow-up. On my side, I tested with a fresh install of ComfyUI v0.19.3 and the default workflow runs without this error.

Since the traceback shows the call still going through `custom_nodes/comfyui-see-through/see-through/common/modules/layerdiffuse/diffusers_kdiffusion_sdxl.py`, could you try a clean reinstall of the environment? Specifically:

1. Fully remove both `custom_nodes/tk-comfyui-see-through` and any leftover `custom_nodes/comfyui-see-through` folders.
2. Reinstall only the latest `tk-comfyui-see-through` on a fresh ComfyUI v0.19.3.
3. Make sure dependencies are reinstalled (`pip install -r requirements.txt`).

I suspect there is an old/duplicated `comfyui-see-through` directory still being loaded, which is why the `Identity.device` error persists despite the fix. A clean environment should resolve it — please let me know if it still reproduces after the reinstall.

Thanks!

**Comment by dijkstrabc** [comment]
Works after reinstalling custom_nodes/tk-comfyui-see-through, thanks!!
